import type { TraceSourceLocation } from '../traceTypes';

export type TraceSemanticIssueCode =
  | 'EMPTY_TRACE'
  | 'MISSING_SCENE_INIT'
  | 'MISSING_STRUCTURE_CREATE'
  | 'WRONG_STRUCTURE_CREATE'
  | 'DUPLICATE_SCENE_INIT'
  | 'DUPLICATE_STRUCTURE_CREATE'
  | 'WRONG_STRUCTURE_COMMAND'
  | 'ARRAY_LABEL_COUNT_MISMATCH'
  | 'ARRAY_INDEX_OUT_OF_BOUNDS'
  | 'MATRIX_NOT_RECTANGULAR'
  | 'MATRIX_POSITION_OUT_OF_BOUNDS'
  | 'TREE_DUPLICATE_NODE_ID'
  | 'TREE_DUPLICATE_CHILD_ID'
  | 'TREE_ROOT_REQUIRED'
  | 'TREE_ROOT_NOT_FOUND'
  | 'TREE_ROOT_HAS_PARENT'
  | 'TREE_CHILD_NOT_FOUND'
  | 'TREE_NODE_NOT_FOUND'
  | 'TREE_MULTIPLE_PARENTS'
  | 'TREE_CYCLE'
  | 'TREE_UNREACHABLE_NODE'
  | 'TREE_NODE_REFERENCED'
  | 'TREE_ROOT_REMOVAL'
  | 'TREE_INVALID_BOUNDS'
  | 'GRAPH_DUPLICATE_NODE_ID'
  | 'GRAPH_DUPLICATE_EDGE_ID'
  | 'GRAPH_NODE_NOT_FOUND'
  | 'GRAPH_EDGE_NOT_FOUND'
  | 'GRAPH_EDGE_NODE_NOT_FOUND'
  | 'GRAPH_FIXED_POSITIONS_REQUIRED'
  | 'GRAPH_FIXED_POSITION_MISSING'
  | 'GRAPH_POSITION_UNKNOWN_NODE'
  | 'GRAPH_CIRCULAR_POSITIONS_NOT_ALLOWED'
  | 'GRAPH_FIXED_ADD_NODE_POSITION_REQUIRED'
  | 'GRAPH_CIRCULAR_ADD_NODE_POSITION_NOT_ALLOWED'
  | 'GRAPH_NODE_HAS_EDGES'
  | 'STACK_UNDERFLOW'
  | 'STACK_INDEX_OUT_OF_BOUNDS'
  | 'QUEUE_UNDERFLOW'
  | 'QUEUE_INDEX_OUT_OF_BOUNDS'
  | 'LINKED_LIST_DUPLICATE_NODE_ID'
  | 'LINKED_LIST_NODE_NOT_FOUND'
  | 'LINKED_LIST_REFERENCE_NOT_FOUND'
  | 'LINKED_LIST_INVALID_PREVIOUS_POINTER'
  | 'LINKED_LIST_INVALID_HEAD_TAIL'
  | 'LINKED_LIST_INVALID_TOPOLOGY'
  | 'LINKED_LIST_NODE_REFERENCED'
  | 'LINKED_LIST_CIRCULAR_NULL_POINTER'
  | 'HASH_TABLE_DUPLICATE_ENTRY_ID'
  | 'HASH_TABLE_DUPLICATE_KEY'
  | 'HASH_TABLE_ENTRY_NOT_FOUND'
  | 'HASH_TABLE_BUCKET_OUT_OF_BOUNDS';

export type TraceSemanticIssue = {
  readonly commandIndex: number;
  readonly code: TraceSemanticIssueCode;
  readonly message: string;
  readonly path?: readonly PropertyKey[];
  readonly source?: TraceSourceLocation;
};

export type TraceSemanticValidationResult =
  | {
      readonly ok: true;
    }
  | {
      readonly ok: false;
      readonly issues: readonly TraceSemanticIssue[];
    };
